version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms-alice:0.0.1-SNAPSHOT
    container_name: ms-alice

    expose:
      - 8081
    ports:
      - "8081:8081"
    environment:
      TZ: "America/Sao_Paulo"
      PROFILE: ${PROFILE}
      ALICE_SUPABASE_URL: ${ALICE_SUPABASE_URL}
      ALICE_SUPABASE_USER: ${ALICE_SUPABASE_USER}
      ALICE_SUPABASE_PASS: ${ALICE_SUPABASE_PASS}
    volumes:
      - /home/ALICE:/home/ALICE
      - /etc/localtime:/etc/localtime
    networks:
      - microservices

networks:
  microservices:
    external: true
