spring:
  application:
    name: ms-alice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: ${PROFILE}

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080
  servlet:
    context-path: /api


