spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${ALICE_H2_URL}
    username: ${ALICE_H2_USER}
    password: ${ALICE_H2_PASS}
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
