spring:
  application:
    name: ms-alice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: ${PROFILE}

server:
  port: 8081
  servlet:
    context-path: /api


springdoc:
  api-docs:
    path: /api-docs
